// <auto-generated />
using CoasterCredits.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoasterCredits.Migrations
{
    [DbContext(typeof(CoasterCreditsContext))]
    [Migration("20180118050757_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoasterCredits.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ManufacturerLocation");

                    b.Property<string>("ManufacturerName");

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
