// <auto-generated />
using CoasterCredits.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoasterCredits.Migrations
{
    [DbContext(typeof(CoasterCreditsContext))]
    partial class CoasterCreditsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoasterCredits.Models.Coaster", b =>
                {
                    b.Property<int>("CoasterID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("CoasterHeight");

                    b.Property<int>("CoasterInversions");

                    b.Property<float>("CoasterLength");

                    b.Property<string>("CoasterManufacturer");

                    b.Property<string>("CoasterName");

                    b.Property<string>("CoasterPark");

                    b.Property<float>("CoasterSpeed");

                    b.Property<int>("CoasterStatus");

                    b.Property<int>("CoasterStyle");

                    b.Property<int>("CoasterType");

                    b.HasKey("CoasterID");

                    b.ToTable("Coaster");
                });

            modelBuilder.Entity("CoasterCredits.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ManufacturerLocation");

                    b.Property<string>("ManufacturerName");

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("CoasterCredits.Models.Park", b =>
                {
                    b.Property<int>("ParkID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("ParkLatitude");

                    b.Property<string>("ParkLocation");

                    b.Property<float>("ParkLongitude");

                    b.Property<string>("ParkName");

                    b.HasKey("ParkID");

                    b.ToTable("Park");
                });
#pragma warning restore 612, 618
        }
    }
}
